workflows:
  web-release:
    name: F360in Web PWA Release Build
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Setup Flutter
        script: |
          flutter config --no-analytics
          flutter pub get
          
      - name: Build Web
        script: |
          flutter build web --release -v
          
    artifacts:
      - build/web/**

  android-release:
    name: F360in Android Release Build
    environment:
      java: default
      flutter: stable
      groups:
        - android_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
      tag_patterns:
        - pattern: 'v\d+\.\d+\.\d+'
          include: true
    scripts:
      - name: Setup Flutter
        script: |
          flutter config --no-analytics
          flutter pub get
          
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release -v
          
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
